AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends log data from CloudWatch Logs and S3 to New Relic Infrastructure (Cloud integrations) and New Relic Logging
Parameters:
  NRLicenseKey:
    Type: String
    Description: Your NewRelic license key. You may omit it when deploying the function.
    Default: "YOUR_LICENSE_KEY"
    NoEcho: true
  NRLoggingEnabled:
    Type: String
    Description: Determines if logs are forwarded to New Relic Logging
    Default: False
    AllowedValues:
      - True
      - False
  NRInfraLogging:
    Type: String
    Description: Determines if logs are forwarded to New Relic Infrastructure
    Default: True
    AllowedValues:
      - True
      - False
  MemorySize:
    Type: Number
    Description: Memory size for the New Relic Log Ingestion Lambda function
    Default: 128
  Timeout:
    Type: Number
    Description: Timeout for the New Relic Log Ingestion Lambda function
    Default: 30

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NewRelic-log-ingestion
    Description: Send log data from CloudWatch Logs and S3 to New Relic Infrastructure (Cloud Integrations) and New Relic Logging.
    Author: New Relic
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/newrelic/aws-log-ingestion
    SemanticVersion: 2.2.0
    SourceCodeUrl: https://github.com/newrelic/aws-log-ingestion

Resources:
  NewRelicLogIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Description: Sends log data from CloudWatch Logs and S3 to New Relic Infrastructure (Cloud integrations) and New Relic Logging
      Handler: function.lambda_handler
      FunctionName: newrelic-log-ingestion
      MemorySize:
        Ref: MemorySize
      Runtime: python3.7
      Timeout:
        Ref: Timeout
      Environment:
        Variables: 
          LICENSE_KEY: !Ref NRLicenseKey
          LOGGING_ENABLED: !Ref NRLoggingEnabled
          INFRA_ENABLED: !Ref NRInfraLogging

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NewRelicLogIngestionFunction
      Action: lambda:InvokeFunction
      Principal: !Sub logs.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
